version: '3'

# Define services
services:
  # database
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: db_wr
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    volumes:
      - db-data-banking:/var/lib/mysql
    networks:
      - backend

  # zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend

  # Kafka
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - backend

  # eureka service
  eureka-service:
    # Configuration for building the docker image
    build:
      context: eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - backend

  # api
  api:
    # Configuration for building the docker image
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: db_wr
      SPRING_DATASOURCE_PASSWORD: 1q2w3e4r
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8080
    restart: always
    depends_on:
      - mysql
      - eureka-service
      - kafka
    networks:
      - backend

  # payment service
  payment-service:
    # Configuration for building the docker image
    build:
      context: payment
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: db_wr
      SPRING_DATASOURCE_PASSWORD: 1q2w3e4r
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      EUREKA_CLIENT_INSTANCE_NONSECUREPORT: 6566
      SERVER_PORT: 8081
    restart: always
    depends_on:
      - mysql
      - eureka-service
      - kafka
    networks:
      - backend

  # external-api-stub
  external-api:
    # Configuration for building the docker image
    build:
      context: external-api
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment: # Pass environment variables to the service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8088
    restart: always
    depends_on:
      - eureka-service
    networks:
      - backend

  # sms-stub
  sms-service:
    # Configuration for building the docker image
    build:
      context: sms
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment: # Pass environment variables to the service
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8083
    restart: always
    depends_on:
      - eureka-service
    networks:
      - backend

  # voucher
  voucher-service:
    # Configuration for building the docker image
    build:
      context: voucher
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: db_wr
      SPRING_DATASOURCE_PASSWORD: 1q2w3e4r
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      EUREKA_CLIENT_INSTANCE_NONSECUREPORT: 6567
      SERVER_PORT: 8082
      EXTERNAL-API_URL: http://external-api:8088/v1/example/voucher
    restart: always
    depends_on:
      - mysql
      - eureka-service
      - kafka
    networks:
      - backend

# Volumes
volumes:
  db-data-banking:
networks:
  backend:
    driver: bridge