version: '3'

# Define services
services:
  # database
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: db_wr
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    volumes:
      - db-data-banking:/var/lib/mysql
    networks:
      - backend

  # eureka service
  eureka-service:
    # Configuration for building the docker image
    build:
      context: eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - backend

  # api
  api:
    # Configuration for building the docker image
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment: # Pass environment variables to the service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8080
    restart: always
    depends_on:
      - mysql
      - eureka-service
    networks:
      - backend

  # payment service
  payment-service:
    # Configuration for building the docker image
    build:
      context: payment
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: db_wr
      SPRING_DATASOURCE_PASSWORD: 1q2w3e4r
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      EUREKA_CLIENT_INSTANCE_NONSECUREPORT: 6566
      SERVER_PORT: 8081
    restart: always
    depends_on:
      - mysql
      - eureka-service
    networks:
      - backend

# Volumes
volumes:
  db-data-banking:
networks:
  backend:
    driver: bridge